### ISSUE TITLE
"Permission denied" when same name occurs twice in Cargo.toml

### ISSUE THREAD

**Issue by ninegua** [nmattia/naersk#170] opened 2021-04-30 21:26 UTC
This relates to https://github.com/dfinity/agent-rs/pull/162

Basically the `Cargo.toml` of agent-rs had the following:
```
members = [
  ...
  "ic-types/",
  ...
]

[patch.crates-io]
ic-types = { path = "./ic-types", version = "0.1", features = [ "serde" ] }
```

This leads to a "permission denied" failure when using `naersk` to compile it. It was essentially trying to copy `ic_types` sub-directory twice to a target directory, and the second copying failed because file permission was `0444`.

**Comment by nmattia** [comment] 2021-05-04 11:33
Hi @ninegua , can you try with the latest naersk? I can't reproduce your issue, do you have a reproduction I could try?

**Comment by ninegua** [comment] 2021-05-04 16:56
The above reported problem is reproducible with commit version ff6a6c73e1e0ffbf179f6a7a063fbb64e16e9214.

The latest master has a different problem leading to unresolved imports:

```
error[E0432]: unresolved import `ic_types::Principal`
 --> /sources/candid-0.6.21/src/types/reference.rs:4:5
  |
4 | use ic_types::Principal;
  |     ^^^^^^^^^^^^^^^^^^^ no `Principal` in the root
```

I've made a draft PR #172 to reproduce this with master (but can also be rebased to ff6a6c73e1e0ffbf179f6a7a063fbb64e16e9214 to reproduce the above reported problem).

**Comment by nmattia** [comment] 2021-05-06 10:23
Ok I was able to reproduce this:

```
Copying patched source /nix/store/zjfinaq7crzksc8iyqrw875b89nwyk7p-source/./ic-types to /nix/store/nvhpvx3nlfkrp10lqdr5v38bjg904d0m-dummy-src...
cp: cannot create regular file '/nix/store/nvhpvx3nlfkrp10lqdr5v38bjg904d0m-dummy-src/ic-types//Cargo.toml': Permission denied
builder for '/nix/store/1h2hjvxqfdgj72a8h8a6md5ar5cavfp8-dummy-src.drv' failed with exit code 1
```

This is your changes cherry-picked on top of https://github.com/nmattia/naersk/commit/ff6a6c73e1e0ffbf179f6a7a063fbb64e16e9214, with a fix for Darwin (adding `libiconv`). It looks like it's trying to copy the patched source to the store, which indeed isn't going to work. I believe this was fixed by @Ekleog here: https://github.com/nmattia/naersk/pull/136/

The `Principal` issue still stands. IIUC: some dependency, namely `candid`, depends on `ic-types`, but you're telling `candid` to use the local `ic-types` as opposed to the one coming from `crates.io`. Is that correct?

Now, comparing the checksums for the files in your agent-rs branch versus the ones that I find in the nix build directory, I noticed that most files were the same _but_ the `lib.rs` differed. I am guessing that the issue is that the `lib.rs` dirs are kept from the `dummy-src` and not overridden with the ones from the "patch".

Didn't see this use case coming at all, but I'll fix it right now.

**Closed** 2021-05-06 15:48 UTC
